-- AlterTable
ALTER TABLE "fields" ADD COLUMN     "color" TEXT,
ADD COLUMN     "type" TEXT,
ALTER COLUMN "h" SET DEFAULT 0,
ALTER COLUMN "w" SET DEFAULT 0,
ALTER COLUMN "x" SET DEFAULT 0,
ALTER COLUMN "y" SET DEFAULT 0;
